format = "$all"
# ~/.config/starship.toml

[username]
disabled = false
show_always = true
format = "  [$user]($style) in "
style_user = "bold yellow"
style_root = "bold red"

[directory]
truncation_length = 8

[character]
success_symbol = "[](bold green) "
error_symbol = "[✗](bold red) "

[hostname]
ssh_only = true
trim_at = "."
disabled = false
style = "dimmed 214"
